# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\x05infer\"+\n\x0cInferRequest\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\",\n\rInferResponse\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"\"\n\x11PreProcessRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"1\n\x12PreProcessResponse\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"2\n\x13\x41\x66terProcessRequest\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\")\n\x04Pred\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\"2\n\x14\x41\x66terProcessResponse\x12\x1a\n\x05preds\x18\x01 \x03(\x0b\x32\x0b.infer.Pred2;\n\x05Infer\x12\x32\n\x05Infer\x12\x13.infer.InferRequest\x1a\x14.infer.InferResponse2\x95\x01\n\x07Process\x12\x41\n\nPreProcess\x12\x18.infer.PreProcessRequest\x1a\x19.infer.PreProcessResponse\x12G\n\x0c\x41\x66terProcess\x12\x1a.infer.AfterProcessRequest\x1a\x1b.infer.AfterProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERREQUEST']._serialized_start=22
  _globals['_INFERREQUEST']._serialized_end=65
  _globals['_INFERRESPONSE']._serialized_start=67
  _globals['_INFERRESPONSE']._serialized_end=111
  _globals['_PREPROCESSREQUEST']._serialized_start=113
  _globals['_PREPROCESSREQUEST']._serialized_end=147
  _globals['_PREPROCESSRESPONSE']._serialized_start=149
  _globals['_PREPROCESSRESPONSE']._serialized_end=198
  _globals['_AFTERPROCESSREQUEST']._serialized_start=200
  _globals['_AFTERPROCESSREQUEST']._serialized_end=250
  _globals['_PRED']._serialized_start=252
  _globals['_PRED']._serialized_end=293
  _globals['_AFTERPROCESSRESPONSE']._serialized_start=295
  _globals['_AFTERPROCESSRESPONSE']._serialized_end=345
  _globals['_INFER']._serialized_start=347
  _globals['_INFER']._serialized_end=406
  _globals['_PROCESS']._serialized_start=409
  _globals['_PROCESS']._serialized_end=558
# @@protoc_insertion_point(module_scope)
